/**
 * @fileoverview gRPC-Web generated client stub for chat
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.1
// source: chat.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as chat_pb from './chat_pb'; // proto import: "chat.proto"


export class ChatServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateRoom = new grpcWeb.MethodDescriptor(
    '/chat.ChatService/CreateRoom',
    grpcWeb.MethodType.UNARY,
    chat_pb.CreateRoomRequest,
    chat_pb.CreateRoomResponse,
    (request: chat_pb.CreateRoomRequest) => {
      return request.serializeBinary();
    },
    chat_pb.CreateRoomResponse.deserializeBinary
  );

  createRoom(
    request: chat_pb.CreateRoomRequest,
    metadata?: grpcWeb.Metadata | null): Promise<chat_pb.CreateRoomResponse>;

  createRoom(
    request: chat_pb.CreateRoomRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: chat_pb.CreateRoomResponse) => void): grpcWeb.ClientReadableStream<chat_pb.CreateRoomResponse>;

  createRoom(
    request: chat_pb.CreateRoomRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: chat_pb.CreateRoomResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/chat.ChatService/CreateRoom',
        request,
        metadata || {},
        this.methodDescriptorCreateRoom,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/chat.ChatService/CreateRoom',
    request,
    metadata || {},
    this.methodDescriptorCreateRoom);
  }

  methodDescriptorJoinRoom = new grpcWeb.MethodDescriptor(
    '/chat.ChatService/JoinRoom',
    grpcWeb.MethodType.UNARY,
    chat_pb.JoinRoomRequest,
    chat_pb.JoinRoomResponse,
    (request: chat_pb.JoinRoomRequest) => {
      return request.serializeBinary();
    },
    chat_pb.JoinRoomResponse.deserializeBinary
  );

  joinRoom(
    request: chat_pb.JoinRoomRequest,
    metadata?: grpcWeb.Metadata | null): Promise<chat_pb.JoinRoomResponse>;

  joinRoom(
    request: chat_pb.JoinRoomRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: chat_pb.JoinRoomResponse) => void): grpcWeb.ClientReadableStream<chat_pb.JoinRoomResponse>;

  joinRoom(
    request: chat_pb.JoinRoomRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: chat_pb.JoinRoomResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/chat.ChatService/JoinRoom',
        request,
        metadata || {},
        this.methodDescriptorJoinRoom,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/chat.ChatService/JoinRoom',
    request,
    metadata || {},
    this.methodDescriptorJoinRoom);
  }

}

